---
- name: create wsgi dir
  file: path={{ wsgi_dir }} state=directory

- name: get venv source
  get_url:
    url: https://pypi.python.org/packages/source/v/virtualenv/virtualenv-15.0.1.tar.gz
    dest: "{{ wsgi_dir }}"

- name: extract venv source
  unarchive: src={{ wsgi_dir }}/virtualenv-15.0.1.tar.gz
             dest={{ wsgi_dir }} copy=no

- name: create venv dir
  file: path={{ wsgi_dir }}/venv state=directory

- name: install venv
  command: python3 {{ wsgi_dir }}/virtualenv-15.0.1/virtualenv.py {{ wsgi_dir }}/venv
           creates={{ wsgi_dir }}/venv/bin/activate
  notify:
    - delete venv source

- name: delete git repo
  file: path={{ wsgi_dir }}/{{ app_name  }}
        state=absent
  when: force_update

- name: uninstall app from venv
  command: >
    {{ wsgi_dir }}/venv/bin/pip uninstall {{ app_name  }} -y
    removes={{ wsgi_dir }}/venv/lib/python*/site-packages/{{ app_name  }}

- name: clone git repo
  git: repo={{ app_git }}
       dest={{ wsgi_dir }}/{{ app_name  }}

- name: install app within venv
  command: >
    {{ wsgi_dir }}/venv/bin/pip install {{ wsgi_dir }}/{{ app_name  }}/
    creates={{ wsgi_dir }}/venv/lib/python*/site-packages/{{ app_name  }}

- name: create app config dir
  file: path={{ config_dir }} state=directory

- name: copy wsgi config
  template: src=wsgi-conf.j2 dest={{ wsgi_dir }}/{{ app_name }}.wsgi owner=www-data group=www-data

- name: install apache2
  apt: name=apache2 state=present update_cache=yes

- name: enable app port in apache
  lineinfile: dest=/etc/apache2/ports.conf state=present line="Listen {{ app_port }}"

- name: install mod-wsgi-py3
  apt: name=libapache2-mod-wsgi-py3 state=present update_cache=yes

- name: enable apache mods
  command: a2enmod wsgi headers rewrite

- name: copy apache site config
  template: src=apache-conf.j2 dest=/etc/apache2/sites-available/{{ app_name }}.conf owner=root group=root

- name: enable apache site
  command: a2ensite {{ app_name }}

- name: restart apache2
  service: name=apache2 state=restarted